language: scala
scala:
- 2.11.11
jdk:
- oraclejdk8
script:
- sbt +test
before_deploy:
- pip install --user release-manager==0.3.0
deploy:
  skip_cleanup: true
  provider: script
  script: "./.travis/deploy.sh $TRAVIS_TAG"
  on:
    tags: true
env:
  global:
  - secure: Xkj+6nQQm43Y3G5D2p9QilPQmYy8V25KqqYIMjXxH16l5UEvHz4SMl8+mNJ2pSsfgxwGKOPE0uZf34H9m343CCmJX0npzH4o5SudOuu+HJAYQRd8DDjkd85V2wRgElSXx5bo3741T2PxYy3oIIpSECEg3IaWeMYXho8H2hgWFj9U7L8rZegrIXyqodjjzwrg8Eusw2LjAK4C5BvAnc7e4ENPpbAP/61f0xBupceu0Y39CSb/CEtnDUKIotyZ0p0T8+XjYW09s35/qgjVFEJ1/wDkMDgIqo+DQ4hKh0v/yIqg5lEmJjLxEvokwOAgVu3o9NB5g3v60ajUdwA10XeFU8uc5BvIEDXEjEhwaqQK0iNuL5CoQkcVsszAmVLd8G9NRFnI1Vs825nFf6j3Uw3S6EDkwdVfkCtJEOznID+Bq3cTx4iLrGeTj9gaChNHwa8UynQlCs2OzY6eZw8DQf1wP2d4R1CUS9Uexsn52qnfr9rsmolvOkTeu6wSzomV7whjSxvFnxEVlsEkwj0x94JjoSMwo9eN9AXJYPKBlgvuJUWzCIAGabriGbAANGdrK8d9fWqNIr4LyIL5UavtFeyYuDhPjLxeMHGZ3Bhv4reQb0YFgFbd4NIzSL6p7ZwhQwBZdjkDsZfnKv2heHkw6j0X7w6REss3doWwmXrS7a1CEMk=
  - secure: GVgq2/lBvF8kpZ8f5AShFFDNQg3Re10EDe02qQmuqBRNiUk5GRCZ0oivUmLrfn/7AxN95YGoV60QwsQzdEy3DcQT8Q2KnJqa5LGwO0HVm+NSbdJ/G9uqLO+TINL0XOZ267rRAGsLk52edAKZRafk5WwAtO81dnuNyw2dUPO+0PVb+BcnWk554m0AXw0UNEoorVwPJiwyjMm59f4uDts0yb2M+tGrkuKloM6N1iLFSCPwbP+uVg/lwJIi3HoX76j9vpxo6odELSQpbYeJBSBGEi3KaZPPID1L50LUUZsc0TsgRlKUNMc3hern66JncD6NJhnoyGLXPELli0+Cdu2Qz7+7fi7QcF1IUgqJXKfEwYf8bFfAOUcVL+woYSUszPZsVsOWtRhbF999B8xXVgyhWs5nL7sqmiQM90U0GbVpudqM2IhMplFz4UhIHMD5kL6x9RyUXJiBXJpMT1Xq3VIt9uZl8v2iyxK2Vbzi/fP78gIQe4Ub/iZ8faqIY5DCg7mc7ojr4JjDPgsv6v9BYzdR91En05kOm2I8HlmxwXa+2OMI203ie05OSnATHaJ0fYmE7tzGlg1hNiBITzRknh+Ud2vfLv0zN49r/wjF6URaTVtaZiq1Q50Iv0FoQJL5xakMWBkcokhyCzeYpPaIri4DuF1iF7LtK1DBGT9QagHB9rs=
