# Required: local settings
local:
  root_dir : <%= ENV['TRAVIS_BUILD_DIR'] %>

# Required: deployment targets
targets:
  - type     : "awss3"
    access_key_id: <%= ENV['AWS_ACCESS_KEY'] %>
    secret_access_key: <%= ENV['AWS_SECRET_KEY'] %>

# Required: packages to be deployed
packages:
  - name     : "snowflake-loader-assets"
    locations:
    - bucket   : "snowplow-hosted-assets"
      path     : "4-storage/snowflake-loader"
      region   : "eu-west-1"
    - bucket   : "snowplow-hosted-assets-us-east-1"
      path     : "4-storage/snowflake-loader"
      region   : "us-east-1"
    - bucket   : "snowplow-hosted-assets-us-west-1"
      path     : "4-storage/snowflake-loader"
      region   : "us-west-1"
    - bucket   : "snowplow-hosted-assets-us-west-2"
      path     : "4-storage/snowflake-loader"
      region   : "us-west-2"
    - bucket   : "snowplow-hosted-assets-sa-east-1"
      path     : "4-storage/snowflake-loader"
      region   : "sa-east-1"
    - bucket   : "snowplow-hosted-assets-eu-central-1"
      path     : "4-storage/snowflake-loader"
      region   : "eu-central-1"
    - bucket   : "snowplow-hosted-assets-ap-southeast-1"
      path     : "4-storage/snowflake-loader"
      region   : "ap-southeast-1"
    - bucket   : "snowplow-hosted-assets-ap-southeast-2"
      path     : "4-storage/snowflake-loader"
      region   : "ap-southeast-2"
    - bucket   : "snowplow-hosted-assets-ap-northeast-1"
      path     : "4-storage/snowflake-loader"
      region   : "ap-northeast-1"
    - bucket   : "snowplow-hosted-assets-ap-south-1"
      path     : "4-storage/snowflake-loader"
      region   : "ap-south-1"
    - bucket   : "snowplow-hosted-assets-us-east-2"
      path     : "4-storage/snowflake-loader"
      region   : "us-east-2"
    - bucket   : "snowplow-hosted-assets-ca-central-1"
      path     : "4-storage/snowflake-loader"
      region   : "ca-central-1"
    - bucket   : "snowplow-hosted-assets-eu-west-2"
      path     : "4-storage/snowflake-loader"
      region   : "eu-west-2"
    - bucket   : "snowplow-hosted-assets-ap-northeast-2"
      path     : "4-storage/snowflake-loader"
      region   : "ap-northeast-2"

    # Will attempt to overwrite a published entity if one is found
    override : false

    # If the artifact already exists will determine whether or not to fail the release
    continue_on_conflict : false

    # The version of this package
    version  : <%= ENV['TRAVIS_TAG'] %>

    # Required IF '--check-version' is passed: will assert that both versions are the same
    build_version : <%= FUNC['sbt_version(.)'] %>

    build_commands:
      - sbt assembly

    # Required: Artifact
    artifacts:
        # The artifact name is composed like so: {{prefix}}{{version}}{{suffix}}.zip
      - type   : "asis"
        prefix : "snowplow-snowflake-transformer-"
        suffix : ".jar"

        # The binaries to put in the zip
        binary_paths:
          - transformer/target/scala-2.11/snowplow-snowflake-transformer-<%= ENV['TRAVIS_TAG'] %>.jar

      - type   : "asis"
        prefix : "snowplow-snowflake-loader-"
        suffix : ".jar"

        # The binaries to put in the zip
        binary_paths:
          - loader/target/scala-2.11/snowplow-snowflake-loader-<%= ENV['TRAVIS_TAG'] %>.jar
